server: 
  port: 8080

spring: 
  application: 
    name: user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate: 
      ddl-auto: none 
  datasource: 
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
    
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
  instance: 
    prefer-ip-address: true